version: '3.8'

services:
  enset-talentgateway-discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 20s
      retries: 4




  enset-talentgateway-config-service:
    build: ./config-service
    ports:
      - "9999:9999"
    networks:
      - my-network
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-talentgateway-discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      enset-talentgateway-discovery-service:
        condition: service_healthy




  internship-service:
    build: ./internship-service
    ports:
      - "8087:8087"
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-talentgateway-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-talentgateway-config-service:9999
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb2:3306/5ra1?createDatabaseIfNotExist=true
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8087/actuator/health" ]
      interval: 10s
    depends_on:
      enset-talentgateway-discovery-service:
        condition: service_healthy
      enset-talentgateway-config-service:
        condition: service_healthy
      mysqldb2:
        condition: service_healthy



  mysqldb:
    image: mysql:8.0.13
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=5ra1
    networks:
      - my-network
    volumes:
      - my-datavolume:/var/lib/mysql


networks:
  my-network:
    driver: bridge
volumes:
  my-datavolume:

