services:


  task-service :
    build: ./task-service
    container_name: task-service
    ports:
      - "8015:8015"
    expose:
      - "8015"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8015/actuator/health"]
      interval: 10s
