version: '3.8'

services:
  enset-talentgateway-discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 20s
      retries: 4

  usertest-service:
    build: D:/4arctic2/semestre2/springboot/test/usertest-service
    ports:
      - "8019:8019"
    depends_on:
      - mysqldb2
      - enset-talentgateway-config-service
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-talentgateway-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-talentgateway-config-service:9999
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb2:3306/usermicroservice?createDatabaseIfNotExist=true
    networks:
      - my-network

  mysqldb2:
    image: mysql:8.0.13
    container_name: mysqldb2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=usermicroservice
    networks:
      - my-network
    volumes:
      - my-datavolume:/var/lib/mysql


  enset-talentgateway-config-service:
    build: ./config-service
    ports:
      - "9999:9999"
    networks:
      - my-network
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-talentgateway-discovery-service:8761/eureka
    healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
        interval: 10s
        retries: 4
    depends_on:
      enset-talentgateway-discovery-service:
        condition: service_healthy

  enset-talentgateway-gateway-service:
    build: ./gateway-service
    container_name:   enset-talentgateway-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-talentgateway-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-talentgateway-config-service:9999
    networks:
      - my-network
    depends_on:
      enset-talentgateway-config-service:
        condition: service_healthy

  project-service:
    build: ./project-service
    ports:
      - "8010:8010"
    depends_on:
      - usertest-service
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-talentgateway-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-talentgateway-config-service:9999
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb2:3306/talentgateway?createDatabaseIfNotExist=true
    networks:
      - my-network
  front-send-angular:
    build: ../../frontend/talentgatewayFrontEnd
    container_name: front-send-angular
    ports:
      - "80:80"
    expose:
      - "80"
    networks:
        - my-network


networks:
  my-network:
    driver: bridge
volumes:
  my-datavolume: