  services:
    talentgateway-discovery-service:
      build: ./discovery-service
      container_name: discovery-service
      ports:
        - '8761:8761'
      expose:
        - '8761'
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
        interval: 10s
        retries: 4



    internship-service:
      build: ./internship-service
      container_name: internship-service
      ports:
        - "8087:8087"
      expose:
        - "8087"
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8087/actuator/health" ]
        interval: 10s
