spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8010/
          predicates:
            - Path=/project-service/**
        - id: r2
          uri: http://localhost:8019/
          predicates:
            - Path=/users/**
  application:
    name: gateway-service
server:
  port: 8888
